In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

In [10]:
l_scores = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)
l_scores

array([0.96, 0.96, 0.94])

In [11]:
np.average(l_scores)

0.9533333333333333

In [17]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=3)
d_scores

array([0.98, 0.94, 0.96])

In [18]:
np.average(d_scores)

0.96

In [22]:
s_scores = cross_val_score(SVC(), iris.data, iris.target,cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [23]:
np.average(s_scores)

0.96

In [26]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=3)
r_scores

array([0.98, 0.94, 0.98])

In [27]:
np.average(r_scores)

0.9666666666666667