In [1]:
from sklearn import svm ,datasets 
import pandas as pd
import numpy as np
iris = datasets.load_iris()

In [2]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x:iris.target_names[x])
df[40:100]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   
55                5.7               2.8                4.5               1.3   
56                6.3               3.3                4.7               1.6   
57                4.9               2.4                3.3               1.0   
58                6.6               2.9                4.6               1.3   
59                5.2               2.7                3.9               1.4   
60                5.0               2.0                3.5               1.0   
61                5.9               3.0                4.2               1.5   
62                6.0               2.2                4.0               1.0   
63                6.1               2.9                4.7               1.4   
64                5.6               2.9                3.6               1.3   
65                6.7               3.1                4.4               1.4   
66                5.6               3.0                4.5               1.5   
67                5.8               2.7                4.1               1.0   
68                6.2               2.2                4.5               1.5   
69                5.6               2.5                3.9               1.1   
70                5.9               3.2                4.8               1.8   
71                6.1               2.8                4.0               1.3   
72                6.3               2.5                4.9               1.5   
73                6.1               2.8                4.7               1.2   
74                6.4               2.9                4.3               1.3   
75                6.6               3.0                4.4               1.4   
76                6.8               2.8                4.8               1.4   
77                6.7               3.0                5.0               1.7   
78                6.0               2.9                4.5               1.5   
79                5.7               2.6                3.5               1.0   
80                5.5               2.4                3.8               1.1   
81                5.5               2.4                3.7               1.0   
82                5.8               2.7                3.9               1.2   
83                6.0               2.7                5.1               1.6   
84                5.4               3.0                4.5               1.5   
85                6.0               3.4                4.5               1.6   
86                6.7               3.1                4.7               1.5   
87                6.3               2.3                4.4               1.3   
88                5.6               3.0                4.1               1.3   
89  

In [3]:
from sklearn.model_selection import train_test_split,cross_val_score
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [4]:
model = svm.SVC(kernel='rbf',C = 10,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [5]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv = 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [6]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [7]:
cross_val_score(svm.SVC(kernel='linear',C=20,gamma='auto'),iris.data,iris.target,cv = 5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [8]:
kernels = ['rbf','linear']
C = [1,10,20]
avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_scores[kval+'-'+str(cval)] = np.average(cv_scores)
avg_scores
    

{'rbf-1': 0.9800000000000001,
 'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9666666666666668,
 'linear-1': 0.9800000000000001,
 'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666}

In [9]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00103869, 0.0006259 , 0.00076747, 0.00070748, 0.00061979,
        0.0005168 ]),
 'std_fit_time': array([3.53823376e-04, 7.76694987e-05, 6.50210785e-05, 1.49833556e-04,
        1.16504502e-05, 3.29126810e-05]),
 'mean_score_time': array([0.00058374, 0.00036869, 0.00044889, 0.00037484, 0.00033603,
        0.0002914 ]),
 'std_score_time': array([1.73340348e-04, 4.63231040e-05, 7.99130425e-05, 4.60703174e-05,
        4.65643143e-06, 9.99926497e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [10]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001039      0.000354         0.000584        0.000173       1   
1       0.000626      0.000078         0.000369        0.000046       1   
2       0.000767      0.000065         0.000449        0.000080      10   
3       0.000707      0.000150         0.000375        0.000046      10   
4       0.000620      0.000012         0.000336        0.000005      20   
5       0.000517      0.000033         0.000291        0.000010      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [11]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [12]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [13]:
clf.best_score_

0.9800000000000001

In [14]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf             0.98
1       1          rbf             0.98

In [15]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}


In [16]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}