In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [4]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [9]:
model.coef_

array([135.78767123])

In [11]:
model.intercept_

180616.43835616432

In [39]:
model.predict([[5000]])

array([859554.79452055])

In [17]:
import pickle

In [19]:
with open('practice_pickle','wb') as file:
    pickle.dump(model,file)

In [20]:
with open('practice_pickle','rb') as file:
    mp = pickle.load(file)

In [22]:
mp.coef_

array([135.78767123])

In [24]:
mp.intercept_

180616.43835616432

In [37]:
mp.predict([[5000]])

array([859554.79452055])

## Joblib

In [29]:
import joblib

In [30]:
joblib.dump(model,'practice_joblib')

['practice_joblib']

In [31]:
model_load = joblib.load('practice_joblib')

In [33]:
model_load.coef_

array([135.78767123])

In [34]:
model_load.intercept_

180616.43835616432

In [36]:
model_load.predict([[5000]])

array([859554.79452055])